language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t mugon/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true mugon/react-test-app npm run test

after_success:
  - docker build -t mugon/docker-frontend ./frontend
  - docker build -t mugon/docker-backend ./backend
  - docker build -t mugon/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push mugon/docker-frontend
  - docker push mugon/docker-backend
  - docker push mugon/docker-nginx

deploy:
  provider: elasticbeanstalk
  edge: true
  region: "ap-northeast-2"
  app: "docker-fullstack-app"
  env: "Dockerfullstackapp-env"
  bucket_name: elasticbeanstalk-ap-northeast-2-688947791751
  bucket_path: "docker-fullstack-app"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
